// Flag emoji from country code
const flag = (code: string) =>
  String.fromCodePoint(...[...code.toUpperCase()].map(c => 0x1F1E6 - 65 + c.charCodeAt(0)));

export const EU_COUNTRY_CODES = new Set([
  "AT","BE","BG","CY","CZ","DE","DK","EE","ES","FI","FR","GR","HU","IE","IT",
  "LT","LU","LV","MT","NL","PL","PT","RO","SE","SI","SK",
]);

export function getBcPostingZone(countryCode: string, payerType: "individual" | "company"): string {
  const code = countryCode.toUpperCase();
  if (payerType === "individual") return "INDIVIDUAL";
  if (code === "HR") return "HR-COMPANY";
  if (EU_COUNTRY_CODES.has(code)) return "EU-COMPANY";
  return "INO-COMPANY";
}

export interface Country {
  code: string;
  name: string;
  flag: string;
}

export const COUNTRIES: Country[] = [
  { code: "HR", name: "Croatia", flag: flag("HR") },
  { code: "AF", name: "Afghanistan", flag: flag("AF") },
  { code: "AL", name: "Albania", flag: flag("AL") },
  { code: "DZ", name: "Algeria", flag: flag("DZ") },
  { code: "AD", name: "Andorra", flag: flag("AD") },
  { code: "AO", name: "Angola", flag: flag("AO") },
  { code: "AG", name: "Antigua and Barbuda", flag: flag("AG") },
  { code: "AR", name: "Argentina", flag: flag("AR") },
  { code: "AM", name: "Armenia", flag: flag("AM") },
  { code: "AU", name: "Australia", flag: flag("AU") },
  { code: "AT", name: "Austria", flag: flag("AT") },
  { code: "AZ", name: "Azerbaijan", flag: flag("AZ") },
  { code: "BS", name: "Bahamas", flag: flag("BS") },
  { code: "BH", name: "Bahrain", flag: flag("BH") },
  { code: "BD", name: "Bangladesh", flag: flag("BD") },
  { code: "BB", name: "Barbados", flag: flag("BB") },
  { code: "BY", name: "Belarus", flag: flag("BY") },
  { code: "BE", name: "Belgium", flag: flag("BE") },
  { code: "BZ", name: "Belize", flag: flag("BZ") },
  { code: "BJ", name: "Benin", flag: flag("BJ") },
  { code: "BT", name: "Bhutan", flag: flag("BT") },
  { code: "BO", name: "Bolivia", flag: flag("BO") },
  { code: "BA", name: "Bosnia and Herzegovina", flag: flag("BA") },
  { code: "BW", name: "Botswana", flag: flag("BW") },
  { code: "BR", name: "Brazil", flag: flag("BR") },
  { code: "BN", name: "Brunei", flag: flag("BN") },
  { code: "BG", name: "Bulgaria", flag: flag("BG") },
  { code: "BF", name: "Burkina Faso", flag: flag("BF") },
  { code: "BI", name: "Burundi", flag: flag("BI") },
  { code: "CV", name: "Cabo Verde", flag: flag("CV") },
  { code: "KH", name: "Cambodia", flag: flag("KH") },
  { code: "CM", name: "Cameroon", flag: flag("CM") },
  { code: "CA", name: "Canada", flag: flag("CA") },
  { code: "CF", name: "Central African Republic", flag: flag("CF") },
  { code: "TD", name: "Chad", flag: flag("TD") },
  { code: "CL", name: "Chile", flag: flag("CL") },
  { code: "CN", name: "China", flag: flag("CN") },
  { code: "CO", name: "Colombia", flag: flag("CO") },
  { code: "KM", name: "Comoros", flag: flag("KM") },
  { code: "CG", name: "Congo", flag: flag("CG") },
  { code: "CD", name: "Congo (DRC)", flag: flag("CD") },
  { code: "CR", name: "Costa Rica", flag: flag("CR") },
  { code: "CI", name: "Côte d'Ivoire", flag: flag("CI") },
  { code: "CU", name: "Cuba", flag: flag("CU") },
  { code: "CY", name: "Cyprus", flag: flag("CY") },
  { code: "CZ", name: "Czech Republic", flag: flag("CZ") },
  { code: "DK", name: "Denmark", flag: flag("DK") },
  { code: "DJ", name: "Djibouti", flag: flag("DJ") },
  { code: "DM", name: "Dominica", flag: flag("DM") },
  { code: "DO", name: "Dominican Republic", flag: flag("DO") },
  { code: "EC", name: "Ecuador", flag: flag("EC") },
  { code: "EG", name: "Egypt", flag: flag("EG") },
  { code: "SV", name: "El Salvador", flag: flag("SV") },
  { code: "GQ", name: "Equatorial Guinea", flag: flag("GQ") },
  { code: "ER", name: "Eritrea", flag: flag("ER") },
  { code: "EE", name: "Estonia", flag: flag("EE") },
  { code: "SZ", name: "Eswatini", flag: flag("SZ") },
  { code: "ET", name: "Ethiopia", flag: flag("ET") },
  { code: "FJ", name: "Fiji", flag: flag("FJ") },
  { code: "FI", name: "Finland", flag: flag("FI") },
  { code: "FR", name: "France", flag: flag("FR") },
  { code: "GA", name: "Gabon", flag: flag("GA") },
  { code: "GM", name: "Gambia", flag: flag("GM") },
  { code: "GE", name: "Georgia", flag: flag("GE") },
  { code: "DE", name: "Germany", flag: flag("DE") },
  { code: "GH", name: "Ghana", flag: flag("GH") },
  { code: "GR", name: "Greece", flag: flag("GR") },
  { code: "GD", name: "Grenada", flag: flag("GD") },
  { code: "GT", name: "Guatemala", flag: flag("GT") },
  { code: "GN", name: "Guinea", flag: flag("GN") },
  { code: "GW", name: "Guinea-Bissau", flag: flag("GW") },
  { code: "GY", name: "Guyana", flag: flag("GY") },
  { code: "HT", name: "Haiti", flag: flag("HT") },
  { code: "HN", name: "Honduras", flag: flag("HN") },
  { code: "HU", name: "Hungary", flag: flag("HU") },
  { code: "IS", name: "Iceland", flag: flag("IS") },
  { code: "IN", name: "India", flag: flag("IN") },
  { code: "ID", name: "Indonesia", flag: flag("ID") },
  { code: "IR", name: "Iran", flag: flag("IR") },
  { code: "IQ", name: "Iraq", flag: flag("IQ") },
  { code: "IE", name: "Ireland", flag: flag("IE") },
  { code: "IL", name: "Israel", flag: flag("IL") },
  { code: "IT", name: "Italy", flag: flag("IT") },
  { code: "JM", name: "Jamaica", flag: flag("JM") },
  { code: "JP", name: "Japan", flag: flag("JP") },
  { code: "JO", name: "Jordan", flag: flag("JO") },
  { code: "KZ", name: "Kazakhstan", flag: flag("KZ") },
  { code: "KE", name: "Kenya", flag: flag("KE") },
  { code: "KI", name: "Kiribati", flag: flag("KI") },
  { code: "KP", name: "North Korea", flag: flag("KP") },
  { code: "KR", name: "South Korea", flag: flag("KR") },
  { code: "XK", name: "Kosovo", flag: flag("XK") },
  { code: "KW", name: "Kuwait", flag: flag("KW") },
  { code: "KG", name: "Kyrgyzstan", flag: flag("KG") },
  { code: "LA", name: "Laos", flag: flag("LA") },
  { code: "LV", name: "Latvia", flag: flag("LV") },
  { code: "LB", name: "Lebanon", flag: flag("LB") },
  { code: "LS", name: "Lesotho", flag: flag("LS") },
  { code: "LR", name: "Liberia", flag: flag("LR") },
  { code: "LY", name: "Libya", flag: flag("LY") },
  { code: "LI", name: "Liechtenstein", flag: flag("LI") },
  { code: "LT", name: "Lithuania", flag: flag("LT") },
  { code: "LU", name: "Luxembourg", flag: flag("LU") },
  { code: "MG", name: "Madagascar", flag: flag("MG") },
  { code: "MW", name: "Malawi", flag: flag("MW") },
  { code: "MY", name: "Malaysia", flag: flag("MY") },
  { code: "MV", name: "Maldives", flag: flag("MV") },
  { code: "ML", name: "Mali", flag: flag("ML") },
  { code: "MT", name: "Malta", flag: flag("MT") },
  { code: "MH", name: "Marshall Islands", flag: flag("MH") },
  { code: "MR", name: "Mauritania", flag: flag("MR") },
  { code: "MU", name: "Mauritius", flag: flag("MU") },
  { code: "MX", name: "Mexico", flag: flag("MX") },
  { code: "FM", name: "Micronesia", flag: flag("FM") },
  { code: "MD", name: "Moldova", flag: flag("MD") },
  { code: "MC", name: "Monaco", flag: flag("MC") },
  { code: "MN", name: "Mongolia", flag: flag("MN") },
  { code: "ME", name: "Montenegro", flag: flag("ME") },
  { code: "MA", name: "Morocco", flag: flag("MA") },
  { code: "MZ", name: "Mozambique", flag: flag("MZ") },
  { code: "MM", name: "Myanmar", flag: flag("MM") },
  { code: "NA", name: "Namibia", flag: flag("NA") },
  { code: "NR", name: "Nauru", flag: flag("NR") },
  { code: "NP", name: "Nepal", flag: flag("NP") },
  { code: "NL", name: "Netherlands", flag: flag("NL") },
  { code: "NZ", name: "New Zealand", flag: flag("NZ") },
  { code: "NI", name: "Nicaragua", flag: flag("NI") },
  { code: "NE", name: "Niger", flag: flag("NE") },
  { code: "NG", name: "Nigeria", flag: flag("NG") },
  { code: "MK", name: "North Macedonia", flag: flag("MK") },
  { code: "NO", name: "Norway", flag: flag("NO") },
  { code: "OM", name: "Oman", flag: flag("OM") },
  { code: "PK", name: "Pakistan", flag: flag("PK") },
  { code: "PW", name: "Palau", flag: flag("PW") },
  { code: "PS", name: "Palestine", flag: flag("PS") },
  { code: "PA", name: "Panama", flag: flag("PA") },
  { code: "PG", name: "Papua New Guinea", flag: flag("PG") },
  { code: "PY", name: "Paraguay", flag: flag("PY") },
  { code: "PE", name: "Peru", flag: flag("PE") },
  { code: "PH", name: "Philippines", flag: flag("PH") },
  { code: "PL", name: "Poland", flag: flag("PL") },
  { code: "PT", name: "Portugal", flag: flag("PT") },
  { code: "QA", name: "Qatar", flag: flag("QA") },
  { code: "RO", name: "Romania", flag: flag("RO") },
  { code: "RU", name: "Russia", flag: flag("RU") },
  { code: "RW", name: "Rwanda", flag: flag("RW") },
  { code: "KN", name: "Saint Kitts and Nevis", flag: flag("KN") },
  { code: "LC", name: "Saint Lucia", flag: flag("LC") },
  { code: "VC", name: "Saint Vincent and the Grenadines", flag: flag("VC") },
  { code: "WS", name: "Samoa", flag: flag("WS") },
  { code: "SM", name: "San Marino", flag: flag("SM") },
  { code: "ST", name: "São Tomé and Príncipe", flag: flag("ST") },
  { code: "SA", name: "Saudi Arabia", flag: flag("SA") },
  { code: "SN", name: "Senegal", flag: flag("SN") },
  { code: "RS", name: "Serbia", flag: flag("RS") },
  { code: "SC", name: "Seychelles", flag: flag("SC") },
  { code: "SL", name: "Sierra Leone", flag: flag("SL") },
  { code: "SG", name: "Singapore", flag: flag("SG") },
  { code: "SK", name: "Slovakia", flag: flag("SK") },
  { code: "SI", name: "Slovenia", flag: flag("SI") },
  { code: "SB", name: "Solomon Islands", flag: flag("SB") },
  { code: "SO", name: "Somalia", flag: flag("SO") },
  { code: "ZA", name: "South Africa", flag: flag("ZA") },
  { code: "SS", name: "South Sudan", flag: flag("SS") },
  { code: "ES", name: "Spain", flag: flag("ES") },
  { code: "LK", name: "Sri Lanka", flag: flag("LK") },
  { code: "SD", name: "Sudan", flag: flag("SD") },
  { code: "SR", name: "Suriname", flag: flag("SR") },
  { code: "SE", name: "Sweden", flag: flag("SE") },
  { code: "CH", name: "Switzerland", flag: flag("CH") },
  { code: "SY", name: "Syria", flag: flag("SY") },
  { code: "TW", name: "Taiwan", flag: flag("TW") },
  { code: "TJ", name: "Tajikistan", flag: flag("TJ") },
  { code: "TZ", name: "Tanzania", flag: flag("TZ") },
  { code: "TH", name: "Thailand", flag: flag("TH") },
  { code: "TL", name: "Timor-Leste", flag: flag("TL") },
  { code: "TG", name: "Togo", flag: flag("TG") },
  { code: "TO", name: "Tonga", flag: flag("TO") },
  { code: "TT", name: "Trinidad and Tobago", flag: flag("TT") },
  { code: "TN", name: "Tunisia", flag: flag("TN") },
  { code: "TR", name: "Turkey", flag: flag("TR") },
  { code: "TM", name: "Turkmenistan", flag: flag("TM") },
  { code: "TV", name: "Tuvalu", flag: flag("TV") },
  { code: "UG", name: "Uganda", flag: flag("UG") },
  { code: "UA", name: "Ukraine", flag: flag("UA") },
  { code: "AE", name: "United Arab Emirates", flag: flag("AE") },
  { code: "GB", name: "United Kingdom", flag: flag("GB") },
  { code: "US", name: "United States", flag: flag("US") },
  { code: "UY", name: "Uruguay", flag: flag("UY") },
  { code: "UZ", name: "Uzbekistan", flag: flag("UZ") },
  { code: "VU", name: "Vanuatu", flag: flag("VU") },
  { code: "VA", name: "Vatican City", flag: flag("VA") },
  { code: "VE", name: "Venezuela", flag: flag("VE") },
  { code: "VN", name: "Vietnam", flag: flag("VN") },
  { code: "YE", name: "Yemen", flag: flag("YE") },
  { code: "ZM", name: "Zambia", flag: flag("ZM") },
  { code: "ZW", name: "Zimbabwe", flag: flag("ZW") },
];

export function getCountryName(code: string): string {
  return COUNTRIES.find(c => c.code === code)?.name ?? code;
}
