
export interface Country {
  code: string;
  name: string;
  zone: 'HR' | 'EU' | 'INO';
}

export const COUNTRIES: Country[] = [
  // Croatia first
  { code: 'HR', name: 'Croatia', zone: 'HR' },
  // EU members
  { code: 'AT', name: 'Austria', zone: 'EU' },
  { code: 'BE', name: 'Belgium', zone: 'EU' },
  { code: 'BG', name: 'Bulgaria', zone: 'EU' },
  { code: 'CY', name: 'Cyprus', zone: 'EU' },
  { code: 'CZ', name: 'Czech Republic', zone: 'EU' },
  { code: 'DE', name: 'Germany', zone: 'EU' },
  { code: 'DK', name: 'Denmark', zone: 'EU' },
  { code: 'EE', name: 'Estonia', zone: 'EU' },
  { code: 'ES', name: 'Spain', zone: 'EU' },
  { code: 'FI', name: 'Finland', zone: 'EU' },
  { code: 'FR', name: 'France', zone: 'EU' },
  { code: 'GR', name: 'Greece', zone: 'EU' },
  { code: 'HU', name: 'Hungary', zone: 'EU' },
  { code: 'IE', name: 'Ireland', zone: 'EU' },
  { code: 'IT', name: 'Italy', zone: 'EU' },
  { code: 'LT', name: 'Lithuania', zone: 'EU' },
  { code: 'LU', name: 'Luxembourg', zone: 'EU' },
  { code: 'LV', name: 'Latvia', zone: 'EU' },
  { code: 'MT', name: 'Malta', zone: 'EU' },
  { code: 'NL', name: 'Netherlands', zone: 'EU' },
  { code: 'PL', name: 'Poland', zone: 'EU' },
  { code: 'PT', name: 'Portugal', zone: 'EU' },
  { code: 'RO', name: 'Romania', zone: 'EU' },
  { code: 'SE', name: 'Sweden', zone: 'EU' },
  { code: 'SI', name: 'Slovenia', zone: 'EU' },
  { code: 'SK', name: 'Slovakia', zone: 'EU' },
  // Rest of world (INO) — alphabetical
  { code: 'AF', name: 'Afghanistan', zone: 'INO' },
  { code: 'AL', name: 'Albania', zone: 'INO' },
  { code: 'DZ', name: 'Algeria', zone: 'INO' },
  { code: 'AD', name: 'Andorra', zone: 'INO' },
  { code: 'AO', name: 'Angola', zone: 'INO' },
  { code: 'AG', name: 'Antigua and Barbuda', zone: 'INO' },
  { code: 'AR', name: 'Argentina', zone: 'INO' },
  { code: 'AM', name: 'Armenia', zone: 'INO' },
  { code: 'AU', name: 'Australia', zone: 'INO' },
  { code: 'AZ', name: 'Azerbaijan', zone: 'INO' },
  { code: 'BS', name: 'Bahamas', zone: 'INO' },
  { code: 'BH', name: 'Bahrain', zone: 'INO' },
  { code: 'BD', name: 'Bangladesh', zone: 'INO' },
  { code: 'BB', name: 'Barbados', zone: 'INO' },
  { code: 'BY', name: 'Belarus', zone: 'INO' },
  { code: 'BZ', name: 'Belize', zone: 'INO' },
  { code: 'BJ', name: 'Benin', zone: 'INO' },
  { code: 'BT', name: 'Bhutan', zone: 'INO' },
  { code: 'BO', name: 'Bolivia', zone: 'INO' },
  { code: 'BA', name: 'Bosnia and Herzegovina', zone: 'INO' },
  { code: 'BW', name: 'Botswana', zone: 'INO' },
  { code: 'BR', name: 'Brazil', zone: 'INO' },
  { code: 'BN', name: 'Brunei', zone: 'INO' },
  { code: 'BF', name: 'Burkina Faso', zone: 'INO' },
  { code: 'BI', name: 'Burundi', zone: 'INO' },
  { code: 'CV', name: 'Cabo Verde', zone: 'INO' },
  { code: 'KH', name: 'Cambodia', zone: 'INO' },
  { code: 'CM', name: 'Cameroon', zone: 'INO' },
  { code: 'CA', name: 'Canada', zone: 'INO' },
  { code: 'CF', name: 'Central African Republic', zone: 'INO' },
  { code: 'TD', name: 'Chad', zone: 'INO' },
  { code: 'CL', name: 'Chile', zone: 'INO' },
  { code: 'CN', name: 'China', zone: 'INO' },
  { code: 'CO', name: 'Colombia', zone: 'INO' },
  { code: 'KM', name: 'Comoros', zone: 'INO' },
  { code: 'CG', name: 'Congo', zone: 'INO' },
  { code: 'CD', name: 'Congo (DRC)', zone: 'INO' },
  { code: 'CR', name: 'Costa Rica', zone: 'INO' },
  { code: 'CI', name: "Côte d'Ivoire", zone: 'INO' },
  { code: 'CU', name: 'Cuba', zone: 'INO' },
  { code: 'DJ', name: 'Djibouti', zone: 'INO' },
  { code: 'DM', name: 'Dominica', zone: 'INO' },
  { code: 'DO', name: 'Dominican Republic', zone: 'INO' },
  { code: 'EC', name: 'Ecuador', zone: 'INO' },
  { code: 'EG', name: 'Egypt', zone: 'INO' },
  { code: 'SV', name: 'El Salvador', zone: 'INO' },
  { code: 'GQ', name: 'Equatorial Guinea', zone: 'INO' },
  { code: 'ER', name: 'Eritrea', zone: 'INO' },
  { code: 'SZ', name: 'Eswatini', zone: 'INO' },
  { code: 'ET', name: 'Ethiopia', zone: 'INO' },
  { code: 'FJ', name: 'Fiji', zone: 'INO' },
  { code: 'GA', name: 'Gabon', zone: 'INO' },
  { code: 'GM', name: 'Gambia', zone: 'INO' },
  { code: 'GE', name: 'Georgia', zone: 'INO' },
  { code: 'GH', name: 'Ghana', zone: 'INO' },
  { code: 'GD', name: 'Grenada', zone: 'INO' },
  { code: 'GT', name: 'Guatemala', zone: 'INO' },
  { code: 'GN', name: 'Guinea', zone: 'INO' },
  { code: 'GW', name: 'Guinea-Bissau', zone: 'INO' },
  { code: 'GY', name: 'Guyana', zone: 'INO' },
  { code: 'HT', name: 'Haiti', zone: 'INO' },
  { code: 'HN', name: 'Honduras', zone: 'INO' },
  { code: 'IS', name: 'Iceland', zone: 'INO' },
  { code: 'IN', name: 'India', zone: 'INO' },
  { code: 'ID', name: 'Indonesia', zone: 'INO' },
  { code: 'IR', name: 'Iran', zone: 'INO' },
  { code: 'IQ', name: 'Iraq', zone: 'INO' },
  { code: 'IL', name: 'Israel', zone: 'INO' },
  { code: 'JM', name: 'Jamaica', zone: 'INO' },
  { code: 'JP', name: 'Japan', zone: 'INO' },
  { code: 'JO', name: 'Jordan', zone: 'INO' },
  { code: 'KZ', name: 'Kazakhstan', zone: 'INO' },
  { code: 'KE', name: 'Kenya', zone: 'INO' },
  { code: 'KI', name: 'Kiribati', zone: 'INO' },
  { code: 'KW', name: 'Kuwait', zone: 'INO' },
  { code: 'KG', name: 'Kyrgyzstan', zone: 'INO' },
  { code: 'LA', name: 'Laos', zone: 'INO' },
  { code: 'LB', name: 'Lebanon', zone: 'INO' },
  { code: 'LS', name: 'Lesotho', zone: 'INO' },
  { code: 'LR', name: 'Liberia', zone: 'INO' },
  { code: 'LY', name: 'Libya', zone: 'INO' },
  { code: 'LI', name: 'Liechtenstein', zone: 'INO' },
  { code: 'MG', name: 'Madagascar', zone: 'INO' },
  { code: 'MW', name: 'Malawi', zone: 'INO' },
  { code: 'MY', name: 'Malaysia', zone: 'INO' },
  { code: 'MV', name: 'Maldives', zone: 'INO' },
  { code: 'ML', name: 'Mali', zone: 'INO' },
  { code: 'MH', name: 'Marshall Islands', zone: 'INO' },
  { code: 'MR', name: 'Mauritania', zone: 'INO' },
  { code: 'MU', name: 'Mauritius', zone: 'INO' },
  { code: 'MX', name: 'Mexico', zone: 'INO' },
  { code: 'FM', name: 'Micronesia', zone: 'INO' },
  { code: 'MD', name: 'Moldova', zone: 'INO' },
  { code: 'MC', name: 'Monaco', zone: 'INO' },
  { code: 'MN', name: 'Mongolia', zone: 'INO' },
  { code: 'ME', name: 'Montenegro', zone: 'INO' },
  { code: 'MA', name: 'Morocco', zone: 'INO' },
  { code: 'MZ', name: 'Mozambique', zone: 'INO' },
  { code: 'MM', name: 'Myanmar', zone: 'INO' },
  { code: 'NA', name: 'Namibia', zone: 'INO' },
  { code: 'NR', name: 'Nauru', zone: 'INO' },
  { code: 'NP', name: 'Nepal', zone: 'INO' },
  { code: 'NZ', name: 'New Zealand', zone: 'INO' },
  { code: 'NI', name: 'Nicaragua', zone: 'INO' },
  { code: 'NE', name: 'Niger', zone: 'INO' },
  { code: 'NG', name: 'Nigeria', zone: 'INO' },
  { code: 'KP', name: 'North Korea', zone: 'INO' },
  { code: 'MK', name: 'North Macedonia', zone: 'INO' },
  { code: 'NO', name: 'Norway', zone: 'INO' },
  { code: 'OM', name: 'Oman', zone: 'INO' },
  { code: 'PK', name: 'Pakistan', zone: 'INO' },
  { code: 'PW', name: 'Palau', zone: 'INO' },
  { code: 'PA', name: 'Panama', zone: 'INO' },
  { code: 'PG', name: 'Papua New Guinea', zone: 'INO' },
  { code: 'PY', name: 'Paraguay', zone: 'INO' },
  { code: 'PE', name: 'Peru', zone: 'INO' },
  { code: 'PH', name: 'Philippines', zone: 'INO' },
  { code: 'QA', name: 'Qatar', zone: 'INO' },
  { code: 'RU', name: 'Russia', zone: 'INO' },
  { code: 'RW', name: 'Rwanda', zone: 'INO' },
  { code: 'KN', name: 'Saint Kitts and Nevis', zone: 'INO' },
  { code: 'LC', name: 'Saint Lucia', zone: 'INO' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', zone: 'INO' },
  { code: 'WS', name: 'Samoa', zone: 'INO' },
  { code: 'SM', name: 'San Marino', zone: 'INO' },
  { code: 'ST', name: 'São Tomé and Príncipe', zone: 'INO' },
  { code: 'SA', name: 'Saudi Arabia', zone: 'INO' },
  { code: 'SN', name: 'Senegal', zone: 'INO' },
  { code: 'RS', name: 'Serbia', zone: 'INO' },
  { code: 'SC', name: 'Seychelles', zone: 'INO' },
  { code: 'SL', name: 'Sierra Leone', zone: 'INO' },
  { code: 'SG', name: 'Singapore', zone: 'INO' },
  { code: 'SB', name: 'Solomon Islands', zone: 'INO' },
  { code: 'SO', name: 'Somalia', zone: 'INO' },
  { code: 'ZA', name: 'South Africa', zone: 'INO' },
  { code: 'KR', name: 'South Korea', zone: 'INO' },
  { code: 'SS', name: 'South Sudan', zone: 'INO' },
  { code: 'LK', name: 'Sri Lanka', zone: 'INO' },
  { code: 'SD', name: 'Sudan', zone: 'INO' },
  { code: 'SR', name: 'Suriname', zone: 'INO' },
  { code: 'CH', name: 'Switzerland', zone: 'INO' },
  { code: 'SY', name: 'Syria', zone: 'INO' },
  { code: 'TW', name: 'Taiwan', zone: 'INO' },
  { code: 'TJ', name: 'Tajikistan', zone: 'INO' },
  { code: 'TZ', name: 'Tanzania', zone: 'INO' },
  { code: 'TH', name: 'Thailand', zone: 'INO' },
  { code: 'TL', name: 'Timor-Leste', zone: 'INO' },
  { code: 'TG', name: 'Togo', zone: 'INO' },
  { code: 'TO', name: 'Tonga', zone: 'INO' },
  { code: 'TT', name: 'Trinidad and Tobago', zone: 'INO' },
  { code: 'TN', name: 'Tunisia', zone: 'INO' },
  { code: 'TR', name: 'Turkey', zone: 'INO' },
  { code: 'TM', name: 'Turkmenistan', zone: 'INO' },
  { code: 'TV', name: 'Tuvalu', zone: 'INO' },
  { code: 'UG', name: 'Uganda', zone: 'INO' },
  { code: 'UA', name: 'Ukraine', zone: 'INO' },
  { code: 'AE', name: 'United Arab Emirates', zone: 'INO' },
  { code: 'GB', name: 'United Kingdom', zone: 'INO' },
  { code: 'US', name: 'United States', zone: 'INO' },
  { code: 'UY', name: 'Uruguay', zone: 'INO' },
  { code: 'UZ', name: 'Uzbekistan', zone: 'INO' },
  { code: 'VU', name: 'Vanuatu', zone: 'INO' },
  { code: 'VE', name: 'Venezuela', zone: 'INO' },
  { code: 'VN', name: 'Vietnam', zone: 'INO' },
  { code: 'YE', name: 'Yemen', zone: 'INO' },
  { code: 'ZM', name: 'Zambia', zone: 'INO' },
  { code: 'ZW', name: 'Zimbabwe', zone: 'INO' },
  { code: 'XK', name: 'Kosovo', zone: 'INO' },
  { code: 'PS', name: 'Palestine', zone: 'INO' },
  { code: 'OTHER', name: 'Other', zone: 'INO' },
];

export function getCountryName(code: string): string {
  return COUNTRIES.find(c => c.code === code)?.name ?? code;
}

export function getCountryZone(code: string): 'HR' | 'EU' | 'INO' {
  return COUNTRIES.find(c => c.code === code)?.zone ?? 'INO';
}

export function getBcPostingZone(countryCode: string, payerType: "individual" | "company"): string {
  const zone = getCountryZone(countryCode);
  if (payerType === "individual") return "INDIVIDUAL";
  if (zone === "HR") return "HR-COMPANY";
  if (zone === "EU") return "EU-COMPANY";
  return "INO-COMPANY";
}
