project_id = "yqusqfdaikkvvjflgmmh"

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-ticket-email]
verify_jwt = false

[functions.create-invoice-registration]
verify_jwt = false

[functions.create-order]
verify_jwt = false
